apiVersion: apps/v1
kind: Deployment
metadata:
  name: iac-python-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: iac-python-deployment
  template:
    metadata:
      labels:
        app: iac-python-deployment
    spec:
      containers:
      - name: iac-python
        image: codingforentrepreneurs/iac-python:latest
        env:
        - name: PORT
          value: "8181"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: iac-python-service
spec:
  type: LoadBalancer
  selector:
    app: iac-python-deployment
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8181
